name: CI/CD

on:
  push:
    branches: [trunk]
  pull_request:
    branches: [trunk]

permissions:
  contents: read

jobs:
  Fast:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"
          cache: "npm"
          cache-dependency-path: "package-lock.json"

      - run: npm install

      - run: npm run check

      - run: npm run lint

      - run: npm run test:unit

      - run: npm run build

      - uses: actions/upload-artifact@v4
        with:
          name: build
          path: build

  Slow:
    runs-on: ubuntu-24.04
    needs: [Fast]
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true
          persist-credentials: false

      - uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"
          cache: "npm"
          cache-dependency-path: "package-lock.json"

      - run: npm install

      - run: npx playwright install --with-deps

      - run: npm run test:integration

      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report

  Publish:
    runs-on: ubuntu-24.04
    needs: [Fast]
    if: ${{ !cancelled() && github.ref == 'refs/heads/trunk' }}

    permissions:
      pages: write
      id-token: write

    steps:
      - uses: actions/download-artifact@v4
        with:
          name: build
          path: build

      - uses: actions/upload-pages-artifact@v3
        with:
          path: build

      - uses: actions/deploy-pages@v4
